name: SDF Postgres Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: csv-data
    required: false
  - name: PG_DATABASE
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
  - name: PG_HOST
    inputType: FreeText
    description: ''
    defaultValue: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
