name: SDF Postgres Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: csv-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
